#ifndef EXTIMAGEINFOSEL_H
#define EXTIMAGEINFOSEL_H

#include <QtWidgets/QDialog>
#include "ui_extimageinfosel.h"

#ifdef _WIN32
  #include "windows.h"
#endif //#ifdef _WIN32

#include <vector>
#include "twain.h"
#include "CommonTWAIN.h"

class ExtImageInfoSel : public QDialog
{
  Q_OBJECT

  public:
  ExtImageInfoSel(vector<TW_UINT16> &lstExtImageInfo, QWidget *parent = 0);
  ~ExtImageInfoSel();

  virtual void accept();

  protected:
  vector<TW_UINT16> &m_lstExtImageInfo;

  protected slots:
  //void on_<widget name>_<signal name>(<signal parameters>);
  void on_btnAll_clicked(bool bChecked);
  void on_btnNone_clicked(bool bChecked);
  
  private:
  Ui::ExtImageInfoSelClass ui;
};

const TW_UINT16 kTWEI_TABLE[] =
{
  TWEI_BARCODEX,
  TWEI_BARCODEY,
  TWEI_BARCODETEXT,
  TWEI_BARCODETYPE,
  TWEI_DESHADETOP,
  TWEI_DESHADELEFT,
  TWEI_DESHADEHEIGHT,
  TWEI_DESHADEWIDTH,
  TWEI_DESHADESIZE,
  TWEI_SPECKLESREMOVED,
  TWEI_HORZLINEXCOORD,
  TWEI_HORZLINEYCOORD,
  TWEI_HORZLINELENGTH,
  TWEI_HORZLINETHICKNESS,
  TWEI_VERTLINEXCOORD,
  TWEI_VERTLINEYCOORD,
  TWEI_VERTLINELENGTH,
  TWEI_VERTLINETHICKNESS,
  TWEI_PATCHCODE,
  TWEI_ENDORSEDTEXT,
  TWEI_FORMCONFIDENCE,
  TWEI_FORMTEMPLATEMATCH,
  TWEI_FORMTEMPLATEPAGEMATCH,
  TWEI_FORMHORZDOCOFFSET,
  TWEI_FORMVERTDOCOFFSET,
  TWEI_BARCODECOUNT,
  TWEI_BARCODECONFIDENCE,
  TWEI_BARCODEROTATION,
  TWEI_BARCODETEXTLENGTH,
  TWEI_DESHADECOUNT,
  TWEI_DESHADEBLACKCOUNTOLD,
  TWEI_DESHADEBLACKCOUNTNEW,
  TWEI_DESHADEBLACKRLMIN,
  TWEI_DESHADEBLACKRLMAX,
  TWEI_DESHADEWHITECOUNTOLD,
  TWEI_DESHADEWHITECOUNTNEW,
  TWEI_DESHADEWHITERLMIN,
  TWEI_DESHADEWHITERLAVE,
  TWEI_DESHADEWHITERLMAX,
  TWEI_BLACKSPECKLESREMOVED,
  TWEI_WHITESPECKLESREMOVED,
  TWEI_HORZLINECOUNT,
  TWEI_VERTLINECOUNT,
  TWEI_DESKEWSTATUS,
  TWEI_SKEWORIGINALANGLE,
  TWEI_SKEWFINALANGLE,
  TWEI_SKEWCONFIDENCE,
  TWEI_SKEWWINDOWX1,
  TWEI_SKEWWINDOWY1,
  TWEI_SKEWWINDOWX2,
  TWEI_SKEWWINDOWY2,
  TWEI_SKEWWINDOWX3,
  TWEI_SKEWWINDOWY3,
  TWEI_SKEWWINDOWX4,
  TWEI_SKEWWINDOWY4,
  TWEI_BOOKNAME,
  TWEI_CHAPTERNUMBER,
  TWEI_DOCUMENTNUMBER,
  TWEI_PAGENUMBER,
  TWEI_CAMERA,
  TWEI_FRAMENUMBER,
  TWEI_FRAME,
  TWEI_PIXELFLAVOR,
  TWEI_ICCPROFILE,
  TWEI_LASTSEGMENT,
  TWEI_SEGMENTNUMBER,
  TWEI_MAGDATA,
  TWEI_MAGTYPE,
  TWEI_PAGESIDE,
  TWEI_FILESYSTEMSOURCE,
  TWEI_IMAGEMERGED,
  TWEI_MAGDATALENGTH,
  TWON_DONTCARE16,
};

#endif // EXTIMAGEINFOSEL_H
